import io

def c_repr(s):
    if not s:
        return 'NULL'
    return '"%s"' % str(s).replace('"', '\\"')

keymap = {
    4: ["a", "A"],
    5: ["b", "B"],
    6: ["c", "C"],
    7: ["d", "D"],
    8: ["e", "E"],
    9: ["f", "F"],
    10: ["g", "G"],
    11: ["h", "H"],
    12: ["i", "I"],
    13: ["j", "J"],
    14: ["k", "K"],
    15: ["l", "L"],
    16: ["m", "M"],
    17: ["n", "N"],
    18: ["o", "O"],
    19: ["p", "P"],
    20: ["q", "Q"],
    21: ["r", "R"],
    22: ["s", "S"],
    23: ["t", "T"],
    24: ["u", "U"],
    25: ["v", "V"],
    26: ["w", "W"],
    27: ["x", "X"],
    28: ["y", "Y"],
    29: ["z", "Z"],
    30: ["1", "!"],
    31: ["2", "@"],
    32: ["3", "#"],
    33: ["4", "$"],
    34: ["5", "%"],
    35: ["6", "^"],
    36: ["7", "&"],
    37: ["8", "*"],
    38: ["9", "("],
    39: ["0", ")"],
    40: ["n", "n"],
    41: ["ESCAPE", "ESCAPE"],
    42: ["DELETE|BACKSPACE", "DELETE|BACKSPACE"],
    43: ["TAB", "TAB"],
    44: [" ", " "],
    45: ["-", "_"],
    46: ["=", "+"],
    47: ["[", "{"],
    48: ["]", "}"],
    49: ["", "|"],
    50: ["", ""],
    51: [";", ":"],
    52: ["'", "\""],
    53: ["`", "~"],
    54: [",", "<"],
    55: [".", ">"],
    56: ["/", "?"],
    57: ["CAPSLOCK", "CAPSLOCK"],
    58: ["F1", "F1"],
    59: ["F2", "F2"],
    60: ["F3", "F3"],
    61: ["F4", "F4"],
    62: ["F5", "F5"],
    63: ["F6", "F6"],
    64: ["F7", "F7"],
    65: ["F8", "F8"],
    66: ["F9", "F9"],
    67: ["F10", "F10"],
    68: ["F11", "F11"],
    69: ["F12", "F12"],
    70: ["PRINTSCREEN", "PRINTSCREEN"],
    71: ["SCROLL-LOCK", "SCROLL-LOCK"],
    72: ["PAUSE", "PAUSE"],
    73: ["INSERT", "INSERT"],
    74: ["HOME", "HOME"],
    75: ["PAGEUP", "PAGEUP"],
    76: ["DELETE-FORWARD", "DELETE-FORWARD"],
    77: ["END", "END"],
    78: ["PAGEDOWN", "PAGEDOWN"],
    79: ["RIGHTARROW", "RIGHTARROW"],
    80: ["LEFTARROW", "LEFTARROW"],
    81: ["DOWNARROW", "DOWNARROW"],
    82: ["UPARROW", "UPARROW"],
    83: ["NUMLOCK", "CLEAR"],
    84: ["/", "/"],
    85: ["*", "*"],
    86: ["-", "-"],
    87: ["+", "+"],
    88: ["ENTER", "ENTER"],
    89: ["1", "END"],
    90: ["2", "DOWNARROW"],
    91: ["3", "PAGEDOWN"],
    92: ["4", "LEFTARROW"],
    93: ["5", "5"],
    94: ["6", "RIGHTARROW"],
    95: ["7", "HOME"],
    96: ["8", "UPARROW"],
    97: ["9", "PAGEUP"],
    98: ["0", "INSERT"],
    99: [".", "DELETE"],
    100: ["", ""],
    224: ["LC", "LC"],
    225: ["LS", "LS"],
    226: ["LA", "LA"],
    227: ["LCMD", "LCMD"],
    228: ["RC", "RC"],
    229: ["RS", "RS"],
    230: ["RA", "RA"],
    231: ["RCMD", "RCMD"],
}

sio = io.StringIO()

sio.write('char* KEYMAP[] = {')
for i in range(max(keymap)):
    a, b = keymap.get(i, ('', ''))
    sio.write('%s, %s, ' % (c_repr(a), c_repr(b)))
sio.write('};\n')
sio.write('unsigned int KEYMAP_MAX = %d;\n' % (max(keymap) * 2))

print(sio.getvalue())